# Generated by Django 4.2.4 on 2023-08-26 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0007_remove_user_email_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
