# Generated by Django 4.2.4 on 2023-08-29 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0008_remove_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
