# Generated by Django 4.2.3 on 2023-08-21 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food_app', '0001_initial'),
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.IntegerField()),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('status', models.CharField(choices=[('delivered', 'Delivered'), ('not delivered', 'Not Delivered')], max_length=125)),
                ('delivered_at', models.DateField(auto_now_add=True)),
                ('description', models.CharField(max_length=500)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('delivered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_order', to='users_app.user')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_orderfood', to='food_app.food')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Oreder_orderfood', to='order_app.order')),
            ],
            options={
                'verbose_name': 'Order_food',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='foods',
            field=models.ManyToManyField(related_name='order_food', through='order_app.OrderFood', to='food_app.food'),
        ),
        migrations.AddField(
            model_name='order',
            name='telegram_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_user_order', to='users_app.telegramuser'),
        ),
    ]
