# Generated by Django 4.2.4 on 2023-08-23 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_telegramuser_id_alter_telegramuser_chat_id'),
        ('order_app', '0002_remove_order_telegram_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='telegram_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_user_order', to='users_app.telegramuser'),
            preserve_default=False,
        ),
    ]
