# Generated by Django 4.2.4 on 2023-09-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0004_alter_orderfood_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='lon',
            field=models.FloatField(),
        ),
    ]
