# Generated by Django 4.2.4 on 2023-08-23 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0005_alter_food_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='category_id',
            new_name='category',
        ),
    ]
